### ISSUE TITLE
Start project discussion thread. 

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/project-kejoseph90#1]
@kejoseph90 here's a thread where we can discuss project ideas.

**Comment by nygeog** [comment]
My bad, looks like you added some here: https://github.com/pratt-savi-810/pratt-savi-810.github.io/issues/1

**Comment by nygeog** [comment]
PASTED:

So I thought of a potential project idea that I would like to further develop in this course.

One of my annual projects at NYC Small Business Services is determining whether or not grant applicants for our AvenueNYC program are in CDBG eligible communities. Due to the nature of our grant funding which are provided by HUD.

Every year groups propose a commercial revitalization project and specify the boundaries (site) for which they will be implementing the project. My job is to:

Create a shapefile of the study area
Overlay it with the CDBG eligibility census tract shapefile
Draw a .75 mile (.75 outer boroughs, .25 for Manhattan) buffer using the study are as a shape
Determine whether 50% or more of the tracts within the buffer falls within in CDBG eligible tract
I do this for about 70-100 applicants across the five boroughs. I attached a copy of what these simple maps look like to give you an idea of how this all plays out graphically.
CCI_AveNYC_FY17.pdf
UPROSE_AveNYC_FY17.pdf

**Comment by nygeog** [comment]
[UPROSE_AveNYC_FY17.pdf](https://github.com/pratt-savi-810/project-kejoseph90/files/1420419/UPROSE_AveNYC_FY17.pdf)
[CCI_AveNYC_FY17.pdf](https://github.com/pratt-savi-810/project-kejoseph90/files/1420420/CCI_AveNYC_FY17.pdf)

**Comment by nygeog** [comment]
@kejoseph90 after reading, this sounds like a great project idea, we can discuss more at class!

**Comment by nygeog** [comment]
70-100 applications, personal creates their own study area. 

20sh unique geog's. 

50% or more of tract CDB-eligible communities. 

Manual to based selection.

**Comment by nygeog** [comment]
@kejoseph90 here are the notes I took down in class on Sat. - perhaps you could improve on and further organize them: 

```
input = study area

# include a function for identifying the boro of the project

	study area will need to intresect with borough bounds to get the bb attributes

	if boro_id = 1
		buffer = 100

	elif boro_id = 2
		buffer = 300

	else:
		buffer = 0

	buffer_analysis(buffer_dist)

# include a fucntion to determine if 50% of the tract area within the buffer
	Calculate Field tool to pre calc geometry
	Intersect Study area buffer, w/ tracts
	Calculate Field tool on post-intersected geometry

	if post_calc_geom > (pre_calc) * 0.5:
		then calc_field = "keep"
	
	Select by attriutes where fields = 'Keep'
	

	Count how many tracts within buffer 50% area
	arcpy.frequency_analysis (Group by)


```

**Comment by kejoseph90** [comment]
My repository for my project contents can be found here: 
https://github.com/kejoseph90/Avenue-NYC---CDBG-Eligibility

I have not ran my codes yet to ensure accuracy, there are various questions that I have that will be better suited to discuss in class. 

I was also have trouble creating a buffer intersect tool to read the attributes of the borough boundaries shape.

**Comment by nygeog** [comment]
@kejoseph90 I can't see that repo (it may be private). Please copy your code and work over here for the project so I can view and help edit your code and review it.
